### ISSUE TITLE
Link to my pokemon- list

### ISSUE THREAD

**Issue by K1H1** [htl-perg-2018-19-4ahif/pokemon-list-example-K1H1#1]
https://competent-sinoussi-63f850.netlify.com/pokemon_list.html

**Comment by rstropek** [comment]
Hi @K1H1!

Thank you for the link. Unfortunately, you solution does not yet fully work (e.g. exception in Pokemon list, no data on details page). I recommend fixing these issues because extra points are within reach. Let me know if you need help.

Greetings,
Rainer Stropek.
