### ISSUE TITLE
Details Page

### ISSUE THREAD

**Issue by K1H1** [htl-perg-2018-19-4ahif/pokemon-list-example-K1H1#2]
Hello @rstropek,
I worked at my details page, it is working now:

https://gracious-goldberg-0376b7.netlify.com/pokemon_list.html

**Comment by rstropek** [comment]
Hi @K1H1!

Thank you for your email. I tried your solution. Unfortunately, I got an error when opening a details page:
![image](https://user-images.githubusercontent.com/2341573/51027381-06cc3c00-1591-11e9-9770-66e85e71972b.png)

It seems that there is an error in your code when building the Pokemon API URL.

Greetings,
Rainer Stropek.
